# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on:
  workflow_call:
    inputs:
      digest:
        description: 'The new digest value'
        required: false
        type: string
      tag:
        description: 'The tag to build'
        required: true
        type: string
    secrets:
      DOCKER_PASSWORD:
        required: true

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Handle workflow call or release event
        id: finalize
        run: |
          if [ -n "${{ inputs.digest }}" ]; then
            echo "Triggered by workflow_call with digest: ${{ inputs.digest }}"
          fi
          tag='${{ inputs.tag }}'
          echo "Using the tag $tag"
          nm="befh/go2rtc"
          if [[ $tag == "amd64-latest" ]]; then
            echo "tags=$nm:latest,$nm:amd64-latest,$nm:amd64" >> $GITHUB_OUTPUT
          elif grep -q arm64 <<< $tag; then
            echo "tags=$nm:arm64-latest,$nm:arm64,$nm:$tag" >> $GITHUB_OUTPUT
          else
            echo "tags=$nm:$tag" >> $GITHUB_OUTPUT
          fi
          if grep -q arm64 <<< $tag; then
            echo "arch=linux/arm64" >> $GITHUB_OUTPUT
            mv Dockerfile.arm64 Dockerfile.orig
            sed '1s/arm64v8-latest/${{ inputs.tag }}/' Dockerfile.orig > Dockerfile
          else
            echo "arch=linux/amd64" >> $GITHUB_OUTPUT
            mv Dockerfile Dockerfile.orig
            sed '1s/amd64-latest/${{ inputs.tag }}/' Dockerfile.orig > Dockerfile
          fi
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: befh/go2rtc
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: befh
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.finalize.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ steps.finalize.outputs.arch }}
          context: .
